# Generated by Django 4.2.5 on 2023-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_compare_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
