

// Auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING'
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS'
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const VERIFY_FAIL = 'VERIFY_FAIL'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const REFRESH_FAIL = 'REFRESH_FAIL'
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL'
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS'


// Category

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL'


// Product
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL'
export const GET_PRODUCTS_BY_ARRIVAL_SUCCESS = 'GET_PRODUCTS_BY_ARRIVAL_SUCCESS'
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL'
export const GET_PRODUCTS_BY_SOLD_SUCCESS = 'GET_PRODUCTS_BY_SOLD_SUCCESS'
export const GET_PRODUCTS_BY_SOLD_FAIL = 'GET_PRODUCTS_BY_SOLD_FAIL'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIl'
export const GET_PRODUCTS_CATEGORY_SUCCESS = 'GET_PRODUCTS_CATEGORY_SUCCESS'
export const GET_PRODUCTS_CATEGORY_FAIL = 'GET_PRODUCTS_CATEGORY_FAIL'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'
export const FILTERED_PRODUCTS_SUCCESS = 'FILTERED_PRODUCTS_SUCCESS'
export const FILTERED_PRODUCTS_FAIL = 'FILTERED_PRODUCTS_FAIL'

// Alert 

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'