# Generated by Django 4.2.5 on 2023-09-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("time_to_delivery", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Shipping",
                "verbose_name_plural": "Shipping",
            },
        ),
    ]
